import { AlertCircle, Brain, Pill } from "lucide-react"

export function AIAnalysis({ recordId }: { recordId: string }) {
  // This would normally fetch analysis based on the record ID
  return (
    <div className="space-y-6">
      <div className="rounded-lg border p-4">
        <div className="flex items-start gap-4">
          <div className="rounded-full bg-yellow-100 p-2">
            <AlertCircle className="h-5 w-5 text-yellow-600" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-medium">Vitamin D Deficiency Detected</h3>
            <div className="mt-4 grid gap-2">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-sm font-medium">Your Result</p>
                  <p className="text-sm text-muted-foreground">24 ng/mL</p>
                </div>
                <div>
                  <p className="text-sm font-medium">Normal Range</p>
                  <p className="text-sm text-muted-foreground">30-100 ng/mL</p>
                </div>
              </div>
              <div className="mt-2">
                <p className="text-sm font-medium">AI Analysis</p>
                <p className="text-sm text-muted-foreground">
                  Your Vitamin D level is below the recommended range. This is a common deficiency that can contribute
                  to fatigue, muscle weakness, and bone pain. Low vitamin D levels are also associated with increased
                  risk of depression, impaired immune function, and decreased calcium absorption.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="rounded-lg border p-4">
        <div className="flex items-start gap-4">
          <div className="rounded-full bg-teal-100 p-2">
            <Brain className="h-5 w-5 text-teal-600" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-medium">Potential Health Implications</h3>
            <div className="mt-4">
              <ul className="space-y-2 text-sm text-muted-foreground list-disc list-inside">
                <li>Increased risk of bone fractures and osteoporosis</li>
                <li>Potential contribution to reported fatigue and muscle weakness</li>
                <li>Possible impact on immune system function</li>
                <li>May affect mood and cognitive function</li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div className="rounded-lg border p-4">
        <div className="flex items-start gap-4">
          <div className="rounded-full bg-purple-100 p-2">
            <Pill className="h-5 w-5 text-purple-600" />
          </div>
          <div className="flex-1">
            <h3 className="text-lg font-medium">Recommended Actions</h3>
            <div className="mt-4">
              <ul className="space-y-2 text-sm text-muted-foreground list-disc list-inside">
                <li>
                  <span className="font-medium">Supplementation:</span> Consider taking Vitamin D3 supplements
                  (2000-4000 IU daily)
                </li>
                <li>
                  <span className="font-medium">Diet:</span> Increase consumption of vitamin D-rich foods (fatty fish,
                  egg yolks, fortified foods)
                </li>
                <li>
                  <span className="font-medium">Sunlight:</span> Spend 15-30 minutes in sunlight several times per week
                </li>
                <li>
                  <span className="font-medium">Follow-up:</span> Retest vitamin D levels in 3 months to monitor
                  improvement
                </li>
                <li>
                  <span className="font-medium">Consultation:</span> Consider discussing with an endocrinologist for
                  personalized advice
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div className="rounded-lg border p-4 bg-slate-50">
        <p className="text-sm text-muted-foreground">
          <span className="font-medium">Note:</span> This analysis is generated by AI based on your medical records and
          should be reviewed with a healthcare professional before making any medical decisions.
        </p>
      </div>
    </div>
  )
}
